name: schedule-build

on:
  schedule:
    - cron:  '15 01 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x, 17.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: SetUp
      run: yarn install
      
    - name: Test
      run: yarn test
      
    - name: Build
      run: yarn build
